{
 "title": "Attestation Errors",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Gossip Attestation Errors\n\nBoth aggregated and unaggregated attestations."
   }
  },
  {
   "title": "Beacon Chain Error (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossip_attestation_error_beacon_chain_error[1m])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "\n### Worker Stats\n\n\nStats about the workers that perform the heavy-lifting in gossip consensus message verification.\n"
   }
  },
  {
   "title": "Past Slot (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_past_slot[1m])"
    }
   ]
  },
  {
   "title": "Future Slot (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_future_slot[1m])"
    }
   ]
  },
  {
   "title": "Aggregator not in Committee (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_aggregator_not_in_committee[1m])"
    }
   ]
  },
  {
   "title": "Empty Agg. Bitfield (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_empty_aggregation_bitfield[1m])"
    }
   ]
  },
  {
   "title": "Invalid Selection Proof (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_invalid_selection_proof[1m])"
    }
   ]
  },
  {
   "title": "Invalid Signature (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsubsub_attestation_error_invalid_signature[1m])"
    }
   ]
  },
  {
   "title": "Attestation Already Known (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_attestation_already_known[1m])"
    }
   ]
  },
  {
   "title": "Pubkey Unknown (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_aggregator_pubkey_unknown[1m])"
    }
   ]
  },
  {
   "title": "Prior Attestation Known (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_prior_attestation_known[1m])"
    }
   ]
  },
  {
   "title": "Validator Index Too High (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_validator_index_too_high[1m])"
    }
   ]
  },
  {
   "title": "Aggregator Already Known (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_aggregator_already_known[1m])"
    }
   ]
  },
  {
   "title": "Unknown Target Root (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_unknown_target_root[1m])"
    }
   ]
  },
  {
   "title": "Bad Target Epoch (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_bad_target_epoch[1m])"
    }
   ]
  },
  {
   "title": "Unknown Head Block (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_unknown_head_block[1m])"
    }
   ]
  },
  {
   "title": "Not Exactly One Aggregation Bit Set (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_not_exactly_one_aggregation_bit_set[1m])"
    }
   ]
  },
  {
   "title": "Attests to Future Block (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_attests_to_future_block[1m])"
    }
   ]
  },
  {
   "title": "No Committee for Slot and Index (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_no_committee_for_slot_and_index[1m])"
    }
   ]
  },
  {
   "title": "Invalid State Processing (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_invalid_state_processing[1m])"
    }
   ]
  },
  {
   "title": "Invalid Subnet ID (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "none", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "increase(gossipsub_attestation_error_invalid_subnet_id[1m])"
    }
   ]
  }
 ]
}