{
 "title": "Developer Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "# Developer Summary\n\nA summary dashboard with metrics useful for developers.\n\n         "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Slots since Best Block",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Slots" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_slot - beacon_head_state_slot"
    }
   ]
  },
  {
   "title": "CRIT logs per Minute (BN,VC)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(crit_total[1m])" }
   ]
  },
  {
   "title": "Previous Epoch Attesting Balance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "percentunit", "label": "Percentage of Balance" }
   ],
   "targets": [
    {
     "expr": "beacon_participation_prev_epoch_target_attesting_gwei_total / beacon_participation_prev_epoch_active_gwei_total"
    }
   ]
  },
  {
   "title": "Network Validators (Max)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(beacon_head_state_total_validators_total)"
    }
   ]
  },
  {
   "title": "Local Validators (Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(vc_validators_enabled_count)"
    }
   ]
  },
  {
   "title": "New Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "max(beacon_head_state_total_validators_total) - min(beacon_head_state_total_validators_total)"
    }
   ]
  },
  {
   "title": "Lowest Free Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "min(node_memory_MemAvailable_bytes)"
    }
   ]
  },
  {
   "title": "ERRO logs per Minute (BN,VC)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(error_total[1m])" }
   ]
  },
  {
   "title": "Epoch Boundaries since Finalization (Min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Epochs" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_epoch - beacon_head_state_finalized_epoch"
    }
   ]
  },
  {
   "title": "Inactive Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(beacon_head_state_total_validators_total) - max(beacon_head_state_active_validators_total)"
    }
   ]
  },
  {
   "title": "Highest LH RAM Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(process_resident_memory_bytes)"
    }
   ]
  },
  {
   "title": "Slashed Validators (Network Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(beacon_head_state_slashed_validators_total)"
    }
   ]
  },
  {
   "title": "Lowest Remaining Disk Space",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "min(node_filesystem_free_bytes{mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Biggest Freezer DB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(store_freezer_db_size)" }
   ]
  },
  {
   "title": "Biggest Hot DB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max(store_disk_db_size)" }
   ]
  },
  {
   "title": "Proposer Slashings Received (Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(beacon_processor_work_events_rx_count{type=\"gossip_proposer_slashing\"})"
    }
   ]
  },
  {
   "title": "Attester Slashings Received (Total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(beacon_processor_work_events_rx_count{type=\"gossip_attester_slashing\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 }, "options": { "content": "\n## Host Metrics\n\n" } },
  {
   "title": "Average Load (loadavg 1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node_load1" }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "Filesystem Free Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Beacon Node Resident Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Validator Client Resident Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "libp2p Connected Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Peers" }
   ],
   "targets": [
    { "expr": "libp2p_peers" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "options": {
    "content": "\n## Consensus Message Processing (Beacon Node)\n\n"
   }
  },
  {
   "title": "Head Block Enshrining Delay from Slot Start",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_block_head_slot_start_delay_time_sum[1m])/rate(beacon_block_head_slot_start_delay_time_count[1m])"
    }
   ]
  },
  {
   "title": "Gossip Block Gossip Worker Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"gossip_block\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"gossip_block\"}[1m])"
    }
   ]
  },
  {
   "title": "RPC Block Gossip Worker Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_sum{type=\"rpc_block\"}[1m])\n/\nrate(beacon_processor_worker_time_count{type=\"rpc_block\"}[1m])"
    }
   ]
  },
  {
   "title": "Block Set as Head Too Late (per Min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Late Blocks" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_block_head_slot_start_delay_exceeded_total[1m])"
    }
   ]
  },
  {
   "title": "Count of Attestations for Unknown Head Requeued per Min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_processor_unaggregated_attestation_requeued_total[1m])"
    },
    {
     "expr": "increase(beacon_processor_aggregated_attestation_requeued_total[1m])"
    }
   ]
  },
  {
   "title": "Attestations Delayed by Late Head (per Min)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Threads Unblocked" }
   ],
   "targets": [
    {
     "expr": "increase(beacon_attestation_gate_unblocked_total[1m])"
    }
   ]
  },
  {
   "title": "Beacon Block Sync Aggregate: Set Bits Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    { "expr": "block_sync_aggregate_set_bits" }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 }, "options": { "content": "\n## Validator Monitor\n\n" } },
  {
   "title": "Current Epoch Block Producers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    { "expr": "vc_beacon_block_proposer_count" }
   ]
  },
  {
   "title": "Current Epoch Attesting Validators",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 51 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    {
     "expr": "vc_beacon_attester_count{task = \"current_epoch\"}"
    }
   ]
  },
  {
   "title": "Next Epoch Attesting Validators",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 51 },
   "yaxes": [
    { "format": "none", "label": "Attestation" }
   ],
   "targets": [
    {
     "expr": "vc_beacon_attester_count{task = \"next_epoch\"}"
    }
   ]
  },
  {
   "title": "Prev Epoch On-Chain Inclusion Distance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "none", "label": "Inclusion Distance" }
   ],
   "targets": [
    {
     "expr": "validator_monitor_prev_epoch_on_chain_inclusion_distance"
    }
   ]
  },
  {
   "title": "Attestation was included (Good)",
   "type": "graph",
   "description": "Values are for the previous epoch",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_on_chain_attester_hit[1m])"
    }
   ]
  },
  {
   "title": "Included attestation hit head (Good)",
   "type": "graph",
   "description": "Values are for the previous epoch",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_on_chain_head_attester_hit[1m])"
    }
   ]
  },
  {
   "title": "Included attestation hit target (Good)",
   "type": "graph",
   "description": "Values are for the previous epoch",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_on_chain_target_attester_hit[1m])"
    }
   ]
  },
  {
   "title": "Attestation was NOT included (Bad)",
   "type": "graph",
   "description": "Values are for the previous epoch",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_on_chain_attester_miss[1m])"
    }
   ]
  },
  {
   "title": "Included attestation DID NOT hit head (Bad)",
   "type": "graph",
   "description": "Values are for the previous epoch",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_on_chain_head_attester_miss[1m])"
    }
   ]
  },
  {
   "title": "Included attestation DID NOT hit target (Bad)",
   "type": "graph",
   "description": "Values are for the previous epoch",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(validator_monitor_prev_epoch_on_chain_target_attester_miss[1m])"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 66 }, "options": { "content": "\n## Logging (Beacon Node)\n\n" } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 66 },
   "options": {
    "content": "\n## Logging (Validator Client)\n\n"
   }
  },
  {
   "title": "CRIT logs per Minute (BN)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(crit_total[1m])" }
   ]
  },
  {
   "title": "ERRO logs per Minute (BN)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(error_total[1m])" }
   ]
  },
  {
   "title": "CRIT logs per Minute (VC)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(crit_total[1m])" }
   ]
  },
  {
   "title": "ERRO logs per Minute (VC)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(error_total[1m])" }
   ]
  },
  {
   "title": "WARN logs per Minute (BN)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(warn_total[1m])" }
   ]
  },
  {
   "title": "INFO logs per Minute (BN)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(info_total[1m])" }
   ]
  },
  {
   "title": "WARN logs per Minute (BN)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(warn_total[1m])" }
   ]
  },
  {
   "title": "INFO logs per Minute (BN)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(info_total[1m])" }
   ]
  }
 ]
}